version: '3.7'

services:
  revo-web:
    build:
      context: ./packages/revo-web
    environment:
      - REACT_APP_URL=${REACT_APP_URL}
      - REACT_SERVER_URL=${REACT_SERVER_URL}
    restart: always
    ports:
      - 3002:3002
    container_name: "revo-web"
    depends_on:
      - "revo-server"

  revo-server:
    build:
      context: ./packages/revo-server
    restart: always
    ports:
      - 7002:7002
    environment: 
      - PG_HOST=${PG_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - "revo-postgres"
    container_name: "revo-server"

  revo-postgres:
    image: postgres:14.3
    restart: always
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DEFAULT_DATABASE}
    volumes:
       - ./pgdata:/var/lib/postgresql/data/
    ports:
       - "5433:5432"
